[build]
target = "aarch64-unknown-uefi"
rustflags = ["-C", "link-args=/debug:dwarf", "-C", "soft-float=yes"]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.aarch64-unknown-uefi]
runner="./run.sh"
